### ISSUE TITLE
UnboundLocalError: local variable 'sma_a' referenced before assignment

### ISSUE THREAD

**Issue by JamesPaulKnox** [JamesPaulKnox/doncaster#4]
Checking if "AMCI" is a valid symbol
Fetching historical data for AMCI Acquisition Corp.
Traceback (most recent call last):
  File "create_csv.py", line 55, in <module>
    output = copy.copy(main(i,"5y",30,60,100))
  File "/home/james/projects/doncaster/doncaster_main.py", line 107, in main
    for i in range(0, max(sma_a.count(None),sma_a.count(None),sma_b.count(None),sma_c.count(None),ema_b.count(None),ema_c.count(None))):
UnboundLocalError: local variable 'sma_a' referenced before assignment

**Comment by JamesPaulKnox** [comment]
https://iextrading.com/apps/stocks/AMCI

https://api.iextrading.com/1.0/stock/amci/chart/5y

AMCI appears to be a new company. They registered for their IPO on November 15, 2018. The API returns an empty list. The UI on IEX's site shows no information, other than they exist.
